version: '3'

services:
  login_demo:
    image: gguzelj/7574-login-demo
    ports:
      - 8080:8080
    links:
      - db:demodb
    command: ["/source/wait-for-it.sh", "demodb:3306", "--", "java", "-jar", "/app/demo.jar"]
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=login